- id: 3f3200c407194a77858a438854771435
  alias: Leaving
  trigger:
  - entity_id: group.all_devices
    for:
      minutes: 1
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: sensor.mode
    state: home
  action:
  - data: {}
    service: script.1537733730525
- id: e4ddf14d5ddd462ea12239920684a54f
  alias: Back Door Opens
  trigger:
  - entity_id: sensor.back_door
    from: closed
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: sensor.mode
    state: away
  action:
  - data:
      entity_id: scene.back_door_opens
    service: scene.turn_on
  - data:
      message: Someone opened the back door!
      title: Back Door Opened
    service: notify.browser_adam_pixel
- id: 4e0b8e2a66a141cbb08a6c2c1f88f70a
  alias: Wake Up Light Slowly at 645AM
  trigger:
  - at: 06:45:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      delay_in_sec: 45
      end_level_pct: 50
      entity_id: light.adams_bed_lamp
      start_level_pct: 1
      step_in_level_pct: 1
    service: python_script.fade_in_light
- id: '1537318020901'
  alias: Arriving Home
  trigger:
  - entity_id: group.all_devices
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sensor.mode
    state: away
  action:
  - data: {}
    service: script.1537733751300
- id: '1537791645207'
  alias: Good morning
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - condition: state
    entity_id: sensor.mode
    state: night
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data: {}
    service: script.1537797311402
- id: '1540233472294'
  alias: Tradfri Remote Battery
  trigger:
  - below: '40'
    entity_id: sensor.tradfri_remote_control
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Tradfri Remote low power. Replace Battery ASAP
    service: persistent_notification.create
- id: '1542078433871'
  alias: Motion Detected Away
  trigger:
  - entity_id: binary_sensor.pir_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.mode
    state: away
  action:
  - data:
      data:
        badge: /local/alert-decagram96.png
        icon: /local/alert-decagram96.png
        tag: motion
      message: There is motion detected!
      title: Motion
    service: notify.browser
- id: '1542078666506'
  alias: Button Press 1
  trigger:
  - entity_id: binary_sensor.button
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.mode
    state: home
  - condition: state
    entity_id: sensor.mode
    state: night
  action:
  - data:
      entity_id: light.fastled_ws2811_light
    service: light.toggle
- id: '1542079506478'
  alias: Button Press 2 Home Mode
  trigger:
  - entity_id: binary_sensor.button
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.mode
    state: away
  action:
  - data:
      entity_id: script.1537733751300
    service: script.turn_on
- id: '1545935795147'
  alias: Dim Kitchen Lights When No Motion
  trigger:
  - entity_id: binary_sensor.pir_sensor
    for: 00:05:00
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.mode
    state: home
  - condition: state
    entity_id: light.kitchen_lights
    state: 'on'
  action:
  - data:
      entity_id: script.1546036735190
    service: script.turn_on
- id: '1546147039696'
  alias: Kitchen Dim Automation Off
  trigger:
  - entity_id: light.kitchen_lights
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: automation.dim_kitchen_lights_when_no_motion
    service: automation.turn_off
- id: '1546147178956'
  alias: Kitchen Dim Automation On
  trigger:
  - entity_id: light.kitchen_lights
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: automation.dim_kitchen_lights_when_no_motion
    service: automation.turn_on
