- alias: 'Arriving Home'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'switch.night_mode_active'
        state: 'off'
      - condition: state
        entity_id: 'switch.away_mode_active'
        state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.vd_routine_im_home
          - switch.home_mode_active
    - service: switch.turn_off
      data:
        entity_id: switch.away_mode_active

- alias: 'Leaving'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'switch.night_mode_active'
        state: 'off'
      - condition: state
        entity_id: 'switch.away_mode_active'
        state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.vd_routine_empty_home
          - switch.away_mode_active
    - service: switch.turn_off
      data:
        entity_id: switch.home_mode_active

- alias: 'Back Door Opens'
  trigger:
    platform: state
    entity_id: sensor.back_door
    from: 'closed'
    to: 'open'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'switch.night_mode_active'
        state: 'off'
      - condition: state
        entity_id: 'switch.away_mode_active'
        state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.VD_Routine_Door_Opens
    - service: persistent_notification.create
      data:
        message: Back door intrusion detected at {{ now() }}
        title: Intrusion Detected


- alias: 'Goodnight Switch'
  trigger:
    platform: state
    entity_id: switch.vd_routine_goodnight
    from: 'off'
    to: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.goodnight_switch
