homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 91
  unit_system: imperial
  time_zone: America/Chicago
  customize:
    !include customize.yaml
  auth_providers: 
   - type: homeassistant
   - type: trusted_networks

frontend:
  themes: !include themes.yaml

cloud: !include cloud.yaml

map:

config:

shopping_list:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - '10.0.0.0/24'

websocket_api:

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook: !include logbook.yaml

recorder: 
  purge_keep_days: 7
  db_url: !secret my_db

logger:
  default: info


sun:

cast:

wemo:

python_script:

tts:
  platform: google

group: !include groups.yaml

automation: !include automations.yaml

scene: !include scenes.yaml

script: !include scripts.yaml

mqtt:
  password: !secret mqtt_password
  discovery: true

light:
  !include lights.yaml

switch:
  !include switches.yaml

sensor:
  !include sensors.yaml

binary_sensor:
  !include binary_sensors.yaml

device_tracker:
  !include device_tracker.yaml

zone:
  !include zones.yaml

input_select:
  !include input_select.yaml

camera: !include camera.yaml

weather:
  - platform: darksky
    api_key: !secret darksky_apikey

history_graph: !include history_graph.yaml


notify: !include notify.yaml

rest_command: !include rest_command.yaml

cloudflare:
  email: !secret cloudflare_email
  api_key: !secret cloudflare_key
  zone: starbuckstech.com
  records:
    - home

# remote:
#   - platform: harmony
#     name: Harmony Hub
#     activity: Watch Downstairs Chromecast

climate:
  - platform: generic_thermostat
    name: Bedroom Heat
    heater: switch.wemo_switch_3
    target_sensor: sensor.bedroom_temp
