homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 91
  unit_system: imperial
  time_zone: America/Chicago
  customize:
    !include customize.yaml

frontend:
  themes: !include themes.yaml

map:

config:

shopping_list:

http:
  api_password: !secret http_password

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

tts:
  platform: google

group: !include groups.yaml

automation: !include automations.yaml

scene: !include scenes.yaml

mqtt: #using cloudmqtt.com with a one-way bridge from there https://community.home-assistant.io/t/mqtt-working-mosquitto-cloudmqtt-bridge/1830/52 https://github.com/bastshoes/hass_config
  broker: localhost
  username: pi
  password: raspberry
  discovery: true
  discovery_prefix: smartthings

light:
  !include lights.yaml

switch:
  !include switches.yaml

sensor:
  !include sensors.yaml

binary_sensor:
  !include binary_sensors.yaml

device_tracker:
  !include device_tracker.yaml

camera:
  - platform: mjpeg
    mjpeg_url: !secret streetcamurl
    still_image_url: !secret streetcamurlstill
    name: StreetCam
  - platform: generic
    mjpeg_url: !secret ankercamurl
    still_image_url: !secret ankercamstill
    name: AnkerCam

zone:
  !include zones.yaml

#climate:
#  - platform: generic_thermostat
#    name: Bedroom
#    heater: switch.upstairs_tv #yes I know
#    target_sensor: sensor.bedroom_temp

octoprint:
  host: 10.0.0.227
  api_key: !secret octoprint_key
  bed: true
  number_of_tools: 1


weather:
  - platform: darksky
    api_key: !secret darksky_apikey

history_graph:
  gr1:
    name: Temperatures
    entities:
      - sensor.back_door_temperature
      - sensor.bedroom_temp
      - sensor.cold_ac_air
      - sensor.living_room_temperature
      - sensor.outdoor_temperature
    hours_to_show: 24
    refresh: 60

cast:
  # media_player:
  # - host: 10.0.0.100 #Soundbar
  # - host: 10.0.0.101 #BedroomMini
  # - host: 10.0.0.102 #StarbuckHome
  # - host: 10.0.0.103 #Office Mini
  # - host: 10.0.0.104 #ChromecastBR
  # - host: 10.0.0.105 #Chromecast-Audio
  # - host: 10.0.0.107 #ChromecastUltra

apcupsd:
