homeassistant:
  name: Home
  latitude: 30.567
  longitude: -96.2837
  elevation: 91
  unit_system: imperial
  time_zone: America/Chicago

frontend:

config:

http:
  api_password: !secret http_password

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

media_player:
  - platform: plex

#mqtt:
#  broker: localhost

#light:
#  - platform: mqtt
#    name: "Kitchen"
#    state_topic: "smartthings/kitchen/light/status"
#    command_topic: "smartthings/kitchen/light/switch"
#    brightness_state_topic: 'smartthings/kitchen/light/brightness'
#    brightness_command_topic: 'smartthings/kitchen/light/brightness/set'
#    qos: 0
#    payload_on: "ON"
#    payload_off: "OFF"
#    optimistic: false
#    retain: true

sensor:
  - platform: rest
    name: Living Room Temperature
    resource: http://localhost/
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "°F"
  - platform: rest
    name: Output
    resource: http://10.0.0.35/
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "°F"
  - platform: rest
    name: Intake
    resource: http://10.0.0.30/
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "°F"
  - platform: rest
    name: Bedroom
    resource: http://10.0.0.51/
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "°F"
  - platform: rest
    name: Outside
    resource: http://10.0.0.40/
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: "°F"


camera:
  - platform: mjpeg
    mjpeg_url: http://10.0.0.38:84/cam_get_new.php
    still_image_url: http://10.0.0.38:84/cam_get.php
    name: Outside
