homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 91
  unit_system: imperial
  time_zone: America/Chicago

frontend:

map:

config:

http:
  api_password: !secret http_password

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

tts:
  platform: google

group: !include groups.yaml
#automation: !include automations.yaml

mqtt:
  broker: localhost
  username: pi
  password: raspberry
  discovery: true
  discovery_prefix: smartthings
  
mqtt 2:
  broker: m11.cloudmqtt.com
  port: !secrets cm-port
  username: !secrets cm-username
  password: !secrets cm-password
  

light:
  !include lights.yaml

switch:
  !include switches.yaml

sensor:
  !include sensors.yaml

device_tracker:
  !include device_tracker.yaml

camera:
  - platform: generic
    still_image_url: http://10.0.0.3/bryan-timelapse/latest.jpg
    name: Outside
  - platform: generic
    still_image_url: !secret pupcamurl
    name: PupCam

zone:
  !include zones.yaml
