homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 91
  unit_system: imperial
  time_zone: America/Chicago
  customize:
    !include customize.yaml

frontend:
  themes: !include themes.yaml

map:

config:

shopping_list:

http:
  api_password: !secret http_password

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

tts:
  platform: google

group: !include groups.yaml

automation: !include automations.yaml

scene: !include scenes.yaml

mqtt: #using cloudmqtt.com with a one-way bridge from there https://community.home-assistant.io/t/mqtt-working-mosquitto-cloudmqtt-bridge/1830/52 https://github.com/bastshoes/hass_config
  broker: localhost
  username: pi
  password: raspberry
  discovery: true
  discovery_prefix: smartthings

influxdb:
  host: 127.0.0.1  

light:
  !include lights.yaml

switch:
  !include switches.yaml

sensor:
  !include sensors.yaml

device_tracker:
  !include device_tracker.yaml

camera:
  - platform: generic
    still_image_url: http://10.0.0.38/cam_pic.php
    name: Street
  - platform: generic
    still_image_url: !secret pupcamurl
    name: PupCam

zone:
  !include zones.yaml


# google_assistant:
#   project_id: someproject-2d0b8
#   client_id: !secret google_clientid
#   access_token: !secret google_accesstoken
#   exposed_domains:
#     - switch
#     - light
#     - group

#climate:
#  - platform: generic_thermostat
#    name: Bedroom
#    heater: switch.upstairs_tv #yes I know
#    target_sensor: sensor.bedroom_temp

