homeassistant:
  name: Home
  latitude: 30.567
  longitude: -96.2837
  elevation: 91
  unit_system: imperial
  time_zone: America/Chicago

frontend:

config:

http:
  api_password: !secret http_password

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

sensor:
  platform: yr

tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

media_player:
  - platform: plex

mqtt:
  broker: localhost

light:
  - platform: mqtt
    name: "Kitchen"
    state_topic: "smartthings/kitchen/light/status"
    command_topic: "smartthings/kitchen/light/switch"
    brightness_state_topic: 'smartthings/kitchen/light/brightness'
    brightness_command_topic: 'smartthings/kitchen/light/brightness/set'
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true
