homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 91
  unit_system: imperial
  time_zone: America/Chicago
  customize:
    !include customize.yaml
  auth_providers: 
   - type: homeassistant

frontend:
  themes: !include themes.yaml

automation: !include automations.yaml

binary_sensor: !include binary_sensors.yaml

camera: !include camera.yaml

cast:

cloud: !include cloud.yaml

config:

conversation:

default_config:

device_tracker: !include device_tracker.yaml

discovery:

group: !include groups.yaml

history:

history_graph: !include history_graph.yaml

input_select: !include input_select.yaml

light: !include lights.yaml

logbook: !include logbook.yaml

map:

mobile_app:

notify: !include notify.yaml

person:

python_script:

recorder: !include recorder.yaml

rest_command: !include rest_command.yaml

scene: !include scenes.yaml

script: !include scripts.yaml 

sensor: !include sensors.yaml

shopping_list:

sun:

switch: !include switches.yaml

system_health:

websocket_api:

wemo:

zone: !include zones.yaml

logger:
  default: warn
  logs:
    homeassistant.components.http.view: error

updater:
  include_used_components: true

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  login_attempts_threshold: 5

tts:
  platform: google

mqtt:
  password: !secret mqtt_password
  discovery: true

weather:
  - platform: darksky
    api_key: !secret darksky_apikey

cloudflare:
  email: !secret cloudflare_email
  api_key: !secret cloudflare_key
  zone: starbuckstech.com
  records:
    - home

# remote:
#   - platform: harmony
#     name: Harmony Hub
#     activity: Watch Downstairs Chromecast

# climate:
#   - platform: generic_thermostat
#     name: Bedroom Heat
#     heater: switch.wemo_switch_3
#     target_sensor: sensor.bedroom_temperature2
