#- platform: asuswrt
#  host: 10.0.0.1
#  username: admin
#  password: !secret asus_password
#  protocol: telnet

# - platform: owntracks

- platform: snmp
  host: 10.0.0.1
  community: public
  baseoid: 1.3.6.1.2.1.4.22.1.2
  consider_home: 180
  new_device_defaults: 
    track_new_devices: false

- platform: google_maps
  username: !secret maps_username
  password: !secret maps_password
  consider_home: 180

