- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_ceiling_light_1
    - light.kitchen_ceiling_light_2
    - light.kitchen_ceiling_light_3
    - light.kitchen_ceiling_light_4

- platform: group
  name: Living Room Ceiling Fan
  entities:
    - light.living_room_fan_1
    - light.living_room_fan_2
    - light.living_room_fan_3
    - light.living_room_fan_4

- platform: group
  name: Hallway Light
  entities:
    - light.hallway_light_1
    - light.hallway_light_2

- platform: group
  name: Office Ceiling Light
  entities:
    - light.office_ceiling_light_1
    - light.office_ceiling_light_2
    - light.office_ceiling_light_3
    - light.office_ceiling_light_4

- platform: group
  name: Bedroom Ceiling Light
  entities:
    - light.Bedroom_ceiling_light_1
    - light.Bedroom_ceiling_light_2
    - light.Bedroom_ceiling_light_3
    - light.Bedroom_ceiling_light_4
