- platform: lifx

- platform: mqtt
  name: "Adams Bed Lamp"
  state_topic: "smartthings/Adams Bed Lamp/switch"
  command_topic: "smartthings/Adams Bed Lamp/switch"
  brightness_state_topic: 'smartthings/Adams Bed Lamp/level'
  brightness_command_topic: 'smartthings/Adams Bed Lamp/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Brown Lamp"
  state_topic: "smartthings/Brown Lamp/switch"
  command_topic: "smartthings/Brown Lamp/switch"
  brightness_state_topic: 'smartthings/Brown Lamp/level'
  brightness_command_topic: 'smartthings/Brown Lamp/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100


- platform: mqtt
  name: "Cooking Room Light 1"
  state_topic: "smartthings/Cooking Room Light 1/switch"
  command_topic: "smartthings/Cooking Room Light 1/switch"
  brightness_state_topic: 'smartthings/Cooking Room Light 1/level'
  brightness_command_topic: 'smartthings/Cooking Room Light 1/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Cooking Room Light 2"
  state_topic: "smartthings/Cooking Room Light 2/switch"
  command_topic: "smartthings/Cooking Room Light 2/switch"
  brightness_state_topic: 'smartthings/Cooking Room Light 2/level'
  brightness_command_topic: 'smartthings/Cooking Room Light 2/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Cooking Room Light 3"
  state_topic: "smartthings/Cooking Room Light 3/switch"
  command_topic: "smartthings/Cooking Room Light 3/switch"
  brightness_state_topic: 'smartthings/Cooking Room Light 3/level'
  brightness_command_topic: 'smartthings/Cooking Room Light 3/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Cooking Room Light 4"
  state_topic: "smartthings/Cooking Room Light 4/switch"
  command_topic: "smartthings/Cooking Room Light 4/switch"
  brightness_state_topic: 'smartthings/Cooking Room Light 4/level'
  brightness_command_topic: 'smartthings/Cooking Room Light 4/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Downstairs Bathroom 1"
  state_topic: "smartthings/Downstairs Bathroom 1/switch"
  command_topic: "smartthings/Downstairs Bathroom 1/switch"
  brightness_state_topic: 'smartthings/Downstairs Bathroom 1/level'
  brightness_command_topic: 'smartthings/Downstairs Bathroom 1/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Downstairs Bathroom 2"
  state_topic: "smartthings/Downstairs Bathroom 2/switch"
  command_topic: "smartthings/Downstairs Bathroom 2/switch"
  brightness_state_topic: 'smartthings/Downstairs Bathroom 2/level'
  brightness_command_topic: 'smartthings/Downstairs Bathroom 2/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Hallway Light 1"
  state_topic: "smartthings/Hallway Light 1/switch"
  command_topic: "smartthings/Hallway Light 1/switch"
  brightness_state_topic: 'smartthings/Hallway Light 1/level'
  brightness_command_topic: 'smartthings/Hallway Light 1/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Hallway Light 2"
  state_topic: "smartthings/Hallway Light 2/switch"
  command_topic: "smartthings/Hallway Light 2/switch"
  brightness_state_topic: 'smartthings/Hallway Light 2/level'
  brightness_command_topic: 'smartthings/Hallway Light 2/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Square Lamp"
  state_topic: "smartthings/Square Lamp/switch"
  command_topic: "smartthings/Square Lamp/switch"
  brightness_state_topic: 'smartthings/Square Lamp/level'
  brightness_command_topic: 'smartthings/Square Lamp/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: mqtt
  name: "Stairs Light"
  state_topic: "smartthings/Stairs Light/switch"
  command_topic: "smartthings/Stairs Light/switch"
  brightness_state_topic: 'smartthings/Stairs Light/level'
  brightness_command_topic: 'smartthings/Stairs Light/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

# - platform: mqtt
#   name: "Hanging Light"
#   state_topic: "smartthings/Hanging Light/switch"
#   command_topic: "smartthings/Hanging Light/switch"
#   brightness_state_topic: 'smartthings/Hanging Light/level'
#   brightness_command_topic: 'smartthings/Hanging Light/level'
#   payload_on: "on"
#   payload_off: "off"
#   optimistic: false
#   qos: 0
#   brightness_scale: 100

- platform: mqtt
  name: "Extra Bedroom Light"
  state_topic: "smartthings/Extra Bedroom Light/switch"
  command_topic: "smartthings/Extra Bedroom Light/switch"
  brightness_state_topic: 'smartthings/Extra Bedroom Light/level'
  brightness_command_topic: 'smartthings/Extra Bedroom Light/level'
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  brightness_scale: 100

- platform: group
  name: Kitchen Lights
  entities:
    - light.cooking_room_light_1
    - light.cooking_room_light_2
    - light.cooking_room_light_3
    - light.cooking_room_light_4

- platform: group
  name: Living Room Ceiling Fan
  entities:
    - light.living_room_fan_1
    - light.living_room_fan_2
    - light.living_room_fan_3
    - light.living_room_fan_4
