- platform: template
  sensors:
    mode:
      friendly_name: "Mode"
      value_template: "{% if is_state('input_select.mode', 'Home Mode') %} home {% elif is_state('input_select.mode', 'Away Mode') %} away {% elif is_state('input_select.mode', 'Night Mode') %} night {% endif %}"
      icon_template: "{% if is_state('switch.home_mode_active', 'on') %} mdi:home-heart {% elif is_state('input_select.mode', 'Away Mode') %} mdi:home-outline {% elif is_state('input_select.mode', 'Night Mode') %} mdi:power-sleep {% endif %}"
