- platform: mqtt
  name: "Ceiling Fan"
  state_topic: "smartthings/Ceiling Fan/switch"
  command_topic: "smartthings/Ceiling Fan/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Ceiling Light"
  state_topic: "smartthings/Ceiling Light/switch"
  command_topic: "smartthings/Ceiling Light/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Upstairs TV"
  state_topic: "smartthings/Upstairs TV/switch"
  command_topic: "smartthings/Upstairs TV/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "VD Routine Door Opens"
  state_topic: "smartthings/VD Routine Door Opens/switch"
  command_topic: "smartthings/VD Routine Door Opens/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "VD Routine Empty Home"
  state_topic: "smartthings/VD Routine Empty Home/switch"
  command_topic: "smartthings/VD Routine Empty Home/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "VD Routine Im Home"
  state_topic: "smartthings/VD Routine Im Home/switch"
  command_topic: "smartthings/VD Routine Im Home/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "night_mode_active"
  state_topic: "smartthings/night_mode_active/switch"
  command_topic: "smartthings/night_mode_active/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "away_mode_active"
  state_topic: "smartthings/away_mode_active/switch"
  command_topic: "smartthings/away_mode_active/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "home_mode_active"
  state_topic: "smartthings/home_mode_active/switch"
  command_topic: "smartthings/home_mode_active/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Downstairs Chromecast"
  state_topic: "smartthings/Downstairs Chromecast/switch"
  command_topic: "smartthings/Downstairs Chromecast/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0


- platform: mqtt
  name: "Downstairs TV"
  state_topic: "smartthings/Downstairs TV/switch"
  command_topic: "smartthings/Downstairs TV/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Play Xbox 360"
  state_topic: "smartthings/Play Xbox 360/switch"
  command_topic: "smartthings/Play Xbox 360/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Play Xbox One"
  state_topic: "smartthings/Play Xbox One/switch"
  command_topic: "smartthings/Play Xbox One/switch"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0


