name: My Awesome Home
views:
  - name: Home
    cards:
      - type: entity-filter
        filter:
          - domain: device_tracker
            state: 'home'
        card: glance
        card_config:
          title: Who's Home?
      - type: picture-glance
        image: https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=240&w=495
        title: Living
        entities:
          - light.brown_lamp
          - light.tall_light
          - sensor.front_door
          - sensor.motion_sensor
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: Bedroom
        entities:
          - switch.upstairs_tv
          - light.adams_bed_lamp
          - switch.laura_bed_lamp
          - switch.ceiling_light
          - switch.ceiling_fan
          - sensor.bedroom_temp
          - media_player.upstairs_speaker
          - remote.harmony_hub_2      
      - type: glance
        title: Temperatures
        entities:
          - sensor.living_room_temperature
          - sensor.bedroom_temp
          - sensor.Cold_AC_Air
      - type: entity-filter
        filter:
          - entity_id: '*cooking_room_light*'
        card_config:
          title: Kitchen
      - type: media-control
        entity: media_player.living_room_tv
  - tab_icon: mdi:video-image
    name: Multimedia
    cards:
      - type: camera-preview
        entity: camera.streetcam
      - type: camera-preview
        entity: camera.ankercam
      - type: media-control
        entity: media_player.bedroom
      - type: media-control
        entity: mmedia_player.bedroom_mini
      - type: media-control
        entity: media_player.living_room_tv
      - type: media-control
        entity: media_player.office_mini
      - type: media-control
        entity: media_player.soundbar
      - type: media-control
        entity: media_player.starbuck_home
      - type: media-control
        entity: media_player.upstairs_speaker
  - tab_icon: mdi:lightbulb
    name: Power
    cards:
      - type: entity-filter
        filter:
          - domain: light
            state: 'on'
          - domain: switch
            state: 'on'
        card_config:
          title: Eating power
      - type: history-graph
        entity: history_graph.temperatures
  - tab_icon: mdi:chart-donut
    name: Sensors
    cards:
      - type: glance
        title: UptimeRobot
        entities:
          - binary_sensor.ctop 
          - binary_sensor.deluge
          - binary_sensor.ombi
          - binary_sensor.plexpy
          - binary_sensor.radarr
          - binary_sensor.shield_router 
          - binary_sensor.sonarr
          - binary_sensor.starbuckstech 
      - type: entity-filter
        filter:
          - entity_id: '*octoprint*'
        card_config:
          title: OctoPrint
  - tab_icon: mdi:settings
    name: Debugging
    cards:
      - type: entity-filter
        filter: [{}]
        card_config:
          title: All entities
